### ISSUE TITLE
Question about previewBox settings

### ISSUE THREAD

**Issue by WebCrew** [XHiddenProjects/WebServerAI#2]
**You wrote at the WIKI:**

previewBox | width | **600** | Int | Sets the width of the preview box.
previewBox | height | **600** | Int | Sets the height of the preview box.

**My question (maybe stupid)** 

Can I also specify **width and height** in **%** or with "**auto**", like in **CSS**, or is it only possible with pixel number specifications?

I'm asking because I'm interested in whether **I could make the preview box responsive** in this way.

Kind regards and by the way - **great job**!

Andy

**Comment by XHiddenProjects** [comment]
`wsa --preview` uses pixels since it's a window executed by Javascript. If you want to use CSS size, you can use an IFrame object to change that size. 

1. You can use that by going to _Settings.json_
2. Use this [Configuration table](https://github.com/XHiddenProjects/WebServerAI/wiki/Installation#configuration) to help
3. Scroll down to where you `ui.*`
4. Configure it.

I hope this helps, if you have any questions, please don't hesitate to reach out.

From,
Gavin

**Comment by WebCrew** [comment]
Yes, that's right, I can customize the iFrame with CSS :)
